module.exports = {
    GET_NOTES: "GET_NOTES",
    GET_NOTES_RESPONSE: "GET_NOTES_RESPONSE",
    SAVE_NOTES: "SAVE_NOTES",
    SAVE_NOTES_RESPONSE: "SAVE_NOTES_RESPONSE",
    UPDATE_NOTES: "UPDATE_NOTES",
    UPDATE_NOTES_RESPONSE: "UPDATE_NOTES_RESPONSE",
    DELETE_NOTES: "DELETE_NOTES",
    DELETE_NOTES_RESPONSE: "DELETE_NOTES_RESPONSE",
}
