module.exports = {
    GET_CALENDAR: "GET_CALENDAR",
    GET_CALENDAR_RESPONSE: "GET_CALENDAR_RESPONSE",
    SAVE_CALENDAR: "SAVE_CALENDAR",
    SAVE_CALENDAR_RESPONSE: "SAVE_CALENDAR_RESPONSE",
    UPDATE_CALENDAR: "UPDATE_CALENDAR",
    UPDATE_CALENDAR_RESPONSE: "UPDATE_CALENDAR_RESPONSE",
    DELETE_CALENDAR: "DELETE_CALENDAR",
    DELETE_CALENDAR_RESPONSE: "DELETE_CALENDAR_RESPONSE",
}
